### ISSUE TITLE
Add crate: dfdx

### ISSUE THREAD

**Issue by coreylowman** [anowell/are-we-learning-yet#118]
Please add crate to category: Neural Networks

If you're open to multiple categories, I think dfdx could also be added to Reinforcement Learning (I have some examples of a Deep Q Network and Proximal Policy Optimization).

github: https://github.com/coreylowman/dfdx
crates.io: https://crates.io/crates/dfdx
docs.rs: https://docs.rs/dfdx/latest/dfdx/

**Comment by anowell** [comment]
Resolved by #122
