### ISSUE TITLE
Add crate: Prophet

### ISSUE THREAD

**Issue by Robbepop** [anowell/are-we-learning-yet#12]
Please add [Prophet crate](https://crates.io/crates/prophet) to category: Neural Networks

Prophet is an actively developed simple feedforward, backpropagation neural network with many basic features around those algorithms.

In its current form it is similar to the NN crate that kind of seems to be abandoned.

**Comment by anowell** [comment]
Thanks. Added and should be live already. :-)

**Comment by Robbepop** [comment]
Wow, that was fast. Thanks! :)
