### ISSUE TITLE
Updating the repo description (cache refresh).

### ISSUE THREAD

**Issue by antimora** [anowell/are-we-learning-yet#132]
We would like to refresh Burn repository description. It has been updated to "Burn - A Flexible and Comprehensive Deep Learning Framework in Rust" from  "BURN: Burn Unstoppable Rusty Neurons"

**Comment by anowell** [comment]
By default, it grabs the description from crates.io. if you want a different description, you can add an override for the `description` field to [`_data.yml/crates.yaml`](https://github.com/anowell/are-we-learning-yet/blob/master/_data/crates.yaml)

PR welcome (and typically merged quicker), but I may try to make the change sometime when not in my phone...

**Comment by anowell** [comment]
This appears to have been updated by virtue of crates.io at some point. Closing.
