### ISSUE TITLE
Add crate: CNTK

### ISSUE THREAD

**Issue by usamec** [anowell/are-we-learning-yet#19]
Please add crate to category: Neural Networks

https://crates.io/crates/cntk

**Comment by usamec** [comment]
Bump.

**Comment by anowell** [comment]
Huge apologies. Been moving, and have a pressing deadline sneaking up on me tomorrow. Will get to this immediately after.

**Comment by usamec** [comment]
No problem.

**Comment by anowell** [comment]
Thanks. It's live now. And again, sorry this took a while to get to. On the plus side, I also got CI wired upto update/redeploy weekly (i.e. with update star/download counts), decreasing my maintenance burden. Cheers!
