### ISSUE TITLE
Tutorial for classification on text data

### ISSUE THREAD

**Issue by maciejkula** [anowell/are-we-learning-yet#2]
First of all, thanks for this!

Secondly, I just finished writing a tutorial for doing simple spam or non-spam classification, end-to-end in Rust, aimed at Rust beginners. It works through downloading data, parsing it into a sparse matrix (using a bag-of-words model), fitting a simple linear classifier to it, and cross-validation.

It's at the Rustbridge repo here: https://github.com/rust-community/rustbridge/tree/master/workshops/machine_learning

**Comment by anowell** [comment]
It's great to discover gems like this. I just added it. Thanks.

**Comment by maciejkula** [comment]
Thank you! Tweeted about your page so hopefully you'll get a little more traffic :)
