### ISSUE TITLE
Add QCGPU

### ISSUE THREAD

**Issue by adamisntdead** [anowell/are-we-learning-yet#25]
For the Scientific Computing Libraries - https://github.com/qcgpu/qcgpu-rust

Theres a site too - https://qcgpu.github.io

**Comment by anowell** [comment]
Done. CI/CD should publish the changes within a couple minutes. Thanks.

**Comment by anowell** [comment]
p.s. if you add repo URL to your `Cargo.toml`, then that will get automatically picked up the next time it is re-published (at least weekly)
