### ISSUE TITLE
Add crates: forester, openml, arff?

### ISSUE THREAD

**Issue by mbillingr** [anowell/are-we-learning-yet#29]
Hello there!

I am working on a few machine learning related crates. Now feels like a good time to add them to are-we-learning-yet :)
Unfortunately, I am not sure which categories some of them should go into, or if they should be added at all. That's why I did not simply create a pull request.
The alleged ML crates are:

- [forester](https://crates.io/crates/forester): Random Forests and Decision Trees. This one is easy; the "Decision Trees" category feels like a good match.
- [openml](https://crates.io/crates/openml): An interface to [OpenML](https://www.openml.org/). It handles  data set downloads and running user defined ML algorithms. There does not seem to be a well-matching category<sup>1</sup>. "Data Processing" seems like the best fit, but it is more about pre-processing than data set loading and model verification. Any ideas?
- [arff](https://crates.io/crates/arff) deals with the ARFF file format. I'm not sure if this crate should be added at all because it's just a (de)serialization library. Granted, the file format is machine-learning specific (only used by Weka and OpenML as far I know), but does this make it suitable for are-we-learning-yet?

<sup>1</sup><sub>Maybe it would be appropriate to add a new category, like "Data Sets" or "Evaluation"?</sub>

**Comment by xpe** [comment]
@mbillingr Hello, some time has passed. Now, it looks like the categories you seek do exist:
* http://www.arewelearningyet.com/decision-trees/
* http://www.arewelearningyet.com/data-preprocessing/

Given that "csv" currently lives in "data processing", I think you can put arff in there as well.

Want to file a PR?

**Comment by mbillingr** [comment]
Thanks for the update. I'll see if I can get a PR up.
