### ISSUE TITLE
Add crate: RustaCUDA

### ISSUE THREAD

**Issue by rasa200** [anowell/are-we-learning-yet#46]
Please add crate to category: GPU Computing 

RustaCUDA helps you bring GPU-acceleration to your projects by providing a flexible, easy-to-use interface to the CUDA GPU computing toolkit. RustaCUDA makes it easy to manage GPU memory, transfer data to and from the GPU, and load and launch compute kernels written in any language.

**Comment by anowell** [comment]
Added via #61
