### ISSUE TITLE
Add crate: Emu: a language for GPGPU from Rust

### ISSUE THREAD

**Issue by calebwin** [anowell/are-we-learning-yet#47]
Please add crate to category: GPU Computing 

[crate](https://crates.io/em)
[repo](https://github.com/calebwin/emu)
[docs](https://github.com/calebwin/emu/tree/master/book)

**Comment by calebwin** [comment]
Have you had a chance to look at this?

**Comment by Enet4** [comment]
@calebwin  These requests are often treated faster if you make the pull request yourself.

**Comment by calebwin** [comment]
@Enet4 I just submitted a PR to add the crate https://github.com/anowell/are-we-learning-yet/pull/49

**Comment by anowell** [comment]
Merged. Sry I didn't get to adding it quicker, but yeah, definitely faster with a PR.
