### ISSUE TITLE
Add crate: EANT2

### ISSUE THREAD

**Issue by Geemili** [anowell/are-we-learning-yet#5]
Please add <https://github.com/pengowen123/eant2> to category: Evolution Algorithms

EANT2 is an Evolutionary algorithm that uses the [Common Genetic Encoding (CGE)](https://github.com/pengowen123/cge) to encode neural networks and [CMA-ES](https://github.com/pengowen123/cmaes) as a weight optimizer.

Essentially, EANT2 evolves the topology of the Neural Network and CMA-ES tries to find the optimal weights for each topology.

**Comment by anowell** [comment]
Looks great! Thanks for pointing it out. Let me know if I got something wrong in adding it.

And feel free to reopen this (or a new issue) once it's published on crates.io.
