### ISSUE TITLE
Link to the PlayRust classifier gives a 404

### ISSUE THREAD

**Issue by cfsamson** [anowell/are-we-learning-yet#57]
On the front page under "Additional resources" the first link leads to a 404 unfortunately: 

https://suchin.io/2016/09/13/The-PlayRust-Classifier/

**Comment by remram44** [comment]
I could find the source here: https://github.com/kernelmachine/kernelmachine.github.io.archive/blob/master/_posts/2016-09-13-The-PlayRust-Classifier.md

Apparently @kernelmachine archived his blog and created a new site. I am not aware of a link to the rendered page (it's not in the wayback machine either)

**Comment by quietlychris** [comment]
I removed in the link in PR #78, although if anyone feels strongly about still having this available, we can probably link to the archived page that @remram44 pointed out. If not, I'll close this issue in a couple of days. Thanks!
