### ISSUE TITLE
AeroRust fork

### ISSUE THREAD

**Issue by o0Ignition0o** [anowell/are-we-learning-yet#63]
Hey everyone :)

As part of the [AeroRust unofficial wg](https://github.com/AeroRust/WorkingGroup) I would like to know if it's ok for us to fork this project and use it as a boilerplate for areweinspaceyet.org

The page looks really great, and it would be a pretty cool way to bootstrap our space effort.

Thanks a lot for your time :)

**Comment by anowell** [comment]
Sorry for my ridiculous delay in responding, but I'm happy to see that you didn't wait on me to respond; the areweinspaceyet.org site looks like a good start. 

Fwiw, Are We Learning Yet content is licensed under Creative Commons Attribution 4.0 International with the general thinking that it's mostly just content that I wanted to be easy for other to use and repurpose for the good of the community. CC BY 4.0 [doesn't really try to be a software license](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), and I never stopped to think that the small bits of software (e.g. html templates, jekyll plugin) might be something worth attaching an open-source software license to (fwiw, I usually default to MIT). So if CC BY 4.0 licensing creates friction for areweinspaceyet, let me know, and I could look into licensing the software separate from the content.
