### ISSUE TITLE
Add crate: CRATE

### ISSUE THREAD

**Issue by peter-kehl** [anowell/are-we-learning-yet#74]
Please add these two crates to category: GPU Computing 

`wgpu-rs` is used by `emu` (which is already on `are-we-learning-yet` - thank you). However, I believe `wgpu-rs` deserves its own mention. It supports some GPUs and others are work in progress: https://github.com/gfx-rs/wgpu#supported-platforms.

It contains of three crates:

1.:
- crate `wgpu`
- https://github.com/gfx-rs/wgpu-rs
- https://crates.io/crates/wgpu
- https://docs.rs/wgpu

2. and 3.:
- one GitHub for both crates: https://github.com/gfx-rs/wgpu, which is an "active mirror" of https://hg.mozilla.org/mozilla-central/file/tip/gfx/wgpu.
- first crate: `wgpu-core`:
-- https://crates.io/crates/wgpu-core
-- https://docs.rs/wgpu-core/
- second crate: `wgpu-types`:
-- https://crates.io/crates/wgpu-types
-- https://docs.rs/wgpu-types/

**Comment by quietlychris** [comment]
I've added a `wgpu` link to the GPU Computing topic in PR #78 , although I left out the sub--crates, since it seems relatively easy to find those off of the existing documentation in the wgpu crate. Please feel free to have a look and make/suggest any updates
