### ISSUE TITLE
Add crate: kmeans_colors to clustering

### ISSUE THREAD

**Issue by okaneco** [anowell/are-we-learning-yet#76]
A generic k-means clustering library and command line tool for finding dominant colors in image buffers. It uses kmeans++ initialization and offers implementations of Lloyd's and Hamerly's algorithms for finding k-means.

https://github.com/okaneco/kmeans-colors
https://crates.io/crates/kmeans-colors
https://docs.rs/kmeans_colors/

**Comment by quietlychris** [comment]
@okaneco This crate looks fantastic--would you mind creating a pull request for it? The process for doing so is pretty simple, you can see some examples in the closed pull requests section.

**Comment by quietlychris** [comment]
Actually, I just added it to a different pull request I was putting together, never mind. Will update when that PR is fully merged.

**Comment by quietlychris** [comment]
Added in PR #78
