### ISSUE TITLE
Add section: Metaheuristics

### ISSUE THREAD

**Issue by alfiedotwtf** [anowell/are-we-learning-yet#9]
Not sure if this belongs here, but a new section for Metaheuristics may be warranted.

https://crates.io/crates/metaheuristics

**Comment by anowell** [comment]
Do you know of any other crates that would fit into such a category?

**Comment by alfiedotwtf** [comment]
I've looked, but there aren't that many that I can see apart from what you've got in the EA section. Se yeah, it would look a bit bare sitting in on it's own.

Perhaps change the EA section to actually be Metaheuristics and group them all there (as metaheuristic is a superset of EA)?

**Comment by anowell** [comment]
Good suggestion. EA crates are now under the metaheuristics category. Thanks!

**Comment by alfiedotwtf** [comment]
Awesome :)

Thanks for maintaining an awesome list!
